[[delete-generated-files]]
= 7. Supprimer les fichiers générés

== Principe

Celerio garde une trace de tous les fichiers qu'il génère. À cet effet, Celerio crée et maintient le fichier `.celerio/generated.xml`. Ne modifiez pas et ne supprimez pas ce fichier !

Vous pouvez supprimer les fichiers générés en utilisant le goal `cleanGenerated` du `celerio-maven-plugin`.

Par défaut, tous les fichiers générés qui n'ont pas été modifiés manuellement sont supprimés. Vous pouvez configurer ce plugin pour exclure certains fichiers afin qu'ils ne soient pas supprimés.

== Détails du plugin

=== Nom complet

* name: `com.jaxio.celerio:celerio-maven-plugin`
* goal: `cleanGenerated`
* phase Maven: `clean`

Ce goal utilise le fichier `.celerio/generated.xml` créé par le goal `generate`.

=== Attributs

==== excludedFiles
* valeur par défaut: aucune
* description: Liste les chemins relatifs des fichiers générés qui ne doivent pas être supprimés. Wildcards supportés :
** `?` : correspond à un caractère
** `*` : correspond à zéro ou plusieurs caractères
** `**` : correspond à zéro ou plusieurs répertoires dans un chemin

_Cas d'usage_ : Celerio génère un fichier, vous ne le modifiez pas manuellement, vous le committez dans votre SCM. Pour empêcher Celerio de le supprimer, ajoutez-le à la liste `excludedFiles`.

_Exemple_ :
[source,xml]
----
<configuration>
  <excludedFiles>
    <param>src/main/generated-java/**/domain/**/*.java</param>
  </excludedFiles>
</configuration>
----

==== skip
* expression: `celerio-maven-plugin.cleanGenerated.skip`
* valeur par défaut: `false`
* description: Doit-on ignorer ce goal ?

== Utilisation simple

Dans votre `pom.xml`, créez un profil dédié pour exécuter le plugin, puis lancez :

[source,bash]
----
export JAVA_HOME=/home/herve/jdk-25.0.2+10
mvn -PcleanGen clean
----

Voici le détail du profil `cleanGen` :

[source,xml]
----
<profile>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!-- Delete code generated by Celerio -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <id>cleanGen</id>
  <build>
    <plugins>
      <plugin>
        <groupId>com.jaxio.celerio</groupId>
        <artifactId>celerio-maven-plugin</artifactId>
        <version>${celerio-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>Delete previously generated files (use .celerio/ folder)</id>
            <!-- Si vous ne voulez pas supprimer certains fichiers générés :
            <configuration>
              <excludedFiles>
                <param>src/main/generated-java/**/domain/**/*.java</param>
              </excludedFiles>
            </configuration>
            -->
            <goals>
              <goal>cleanGenerated</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</profile>
----
